name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  now_date_job:
    runs_on: ubuntu-latest
    steps:
      - name: Now it is
        run: |
          date
  
  dir_content_job:
    runs_on: ubuntu-latest
    steps:
      - name: Directory content
        run: |
          ls -l