name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: npm install
        run: npm install

      - name: lint
        run: npm run eslint
        
      - name: build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Run e2e tests
        run: |
          cd e2e-tests
          npm install
          npx playwright install --with-deps
          npm run test
      
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && ! contains(toJson(github.event.head_commit.message), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      
      - name: Test info
          uses: rjstone/discord-webhook-notify@v1
          if: success()
          with:
            severity: info
            details: Test succeeded ฅ^•⩊•^ฅ
            webhookUrl: ${{ secret.DISCORD_WEBHOOK }}

      - name: Test failure
          uses: rjstone/discord-webhook-notify@v1
          if: failture()
          with:
            severity: error
            details: Test failed .^QAQ^.
            webhookUrl: ${{ secret.DISCORD_WEBHOOK }}
      
      - name: Test Cancelled .^0w0^.
          uses: rjstone/discord-webhook-notify@v1
          if: cancelled()
          with:
            severity: warn
            details: Test cancelled 
            webhookUrl: ${{ secret.DISCORD_WEBHOOK }}
      
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && ! contains(toJson(github.event.head_commit.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch